[package]
name = "marian-rust"
version = "0.1.0"
authors = ["Andrew Aldridge <i80and@foxquill.com>"]

[dependencies]
hyper = "0.11"
lazy_static = "0.2.9"
maplit = "1.0"
qp-trie = "0.7"
regex = "0.2"

[profile.release]
lto = true
